echo "<>" > 0-binary_tree_node.c
echo "<>" > 1-binary_tree_insert_left.c
echo "<>" > 2-binary_tree_insert_right.c
echo "<>" > 3-binary_tree_delete.c
echo "<>" > 4-binary_tree_is_leaf.c
echo "<>" > 5-binary_tree_is_root.c
echo "<>" > 6-binary_tree_preorder.c
echo "<>" > 7-binary_tree_inorder.c
echo "<>" > 8-binary_tree_postorder.c
echo "<>" > 9-binary_tree_height.c
echo "<>" > 10-binary_tree_depth.c
echo "<>" > 11-binary_tree_size.c
echo "<>" > 12-binary_tree_leaves.c
echo "<>" > 13-binary_tree_nodes.c
echo "<>" > 14-binary_tree_balance.c
echo "<>" > 15-binary_tree_is_full.c
echo "<>" > 16-binary_tree_is_perfect.c
echo "<>" > 17-binary_tree_sibling.c
echo "<>" > 18-binary_tree_uncle.c
echo "<>" > 100-binary_trees_ancestor.c
echo "<>" > 101-binary_tree_levelorder.c
echo "<>" > 102-binary_tree_is_complete.c
echo "<>" > 103-binary_tree_rotate_left.c
echo "<>" > 104-binary_tree_rotate_right.c
echo "<>" > 110-binary_tree_is_bst.c
echo "<>" > 111-bst_insert.c
echo "<>" > 112-array_to_bst.c
echo "<>" > 113-bst_search.c
echo "<>" > 114-bst_remove.c
echo "<>" > 115-O
echo "<>" > 120-binary_tree_is_avl.c
echo "<>" > 121-avl_insert.c
echo "<>" > 122-array_to_avl.c
echo "<>" > 123-avl_remove.c
echo "<>" > 124-sorted_array_to_avl.c
echo "<>" > 125-O
echo "<>" > 130-binary_tree_is_heap.c
echo "<>" > 131-heap_insert.c
echo "<>" > 132-array_to_heap.c
echo "<>" > 133-heap_extract.c
echo "<>" > 134-heap_to_sorted_array.c
echo "<>" > 135-O

git add .
git commit -m "tasks"
git push
